### ISSUE TITLE
Implement OpenAPI spec and code generation with oapi-codegen

### ISSUE THREAD

**Issue by cedricziel** [cedricziel/mel-agent#50]
## Overview
Implement comprehensive OpenAPI specification and automated code generation using [oapi-codegen](https://github.com/oapi-codegen/oapi-codegen) to improve API documentation, type safety, and developer experience.

## Benefits
- **Type Safety**: Generated Go types prevent runtime errors
- **API Documentation**: Interactive OpenAPI/Swagger docs
- **Client SDK Generation**: Auto-generated client libraries
- **API Contract**: Enforced interface compliance
- **Developer Experience**: IDE autocompletion and validation

## Current API Inventory
Based on codebase analysis, we have **65+ endpoints** across multiple domains:

### Core Endpoints
- **Agent Management**: 8 endpoints (`/api/agents/*`)
- **Workflow Management**: 7 endpoints (`/api/workflows/*`)
- **Workflow Execution**: 5 endpoints (`/api/workflow-runs/*`)
- **Node Types**: 3 endpoints (`/api/node-types/*`)
- **Connections/Credentials**: 7 endpoints (`/api/connections/*`, `/api/credentials/*`)
- **Triggers**: 5 endpoints (`/api/triggers/*`)
- **Workers**: 5 endpoints (`/api/workers/*`)
- **Integrations**: 3 endpoints (`/api/integrations/*`)
- **Extensions**: 1 endpoint (`/api/extensions`)
- **WebSocket**: 1 endpoint (`/api/ws/*`)
- **Health/Webhooks**: 2 endpoints

### Phase 1: Project Setup
1. **Install oapi-codegen**:
   ```bash
   go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest
   ```

2. **Directory Structure**:
   ```
   api/
   ├── openapi.yaml           # Main OpenAPI specification
   ├── config.yaml           # oapi-codegen configuration
   └── generated/
       ├── types.go          # Generated data models
       ├── server.go         # Generated server interfaces
       └── client.go         # Generated client SDK
   ```

3. **Configuration** (`api/config.yaml`):
   ```yaml
   package: generated
   generate:
     chi-server: true
     models: true
     client: true
   output-options:
     skip-fmt: false
     skip-prune: false
   ```

### Phase 2: OpenAPI Specification
Create comprehensive `api/openapi.yaml` covering:

#### **Core API Schemas**
- `Agent`, `Workflow`, `WorkflowRun`, `WorkflowStep`
- `Connection`, `Credential`, `Trigger`
- `NodeType`, `WorkflowNode`, `WorkflowEdge`
- `Worker`, `QueueItem`, `Integration`

#### **Request/Response Objects**
- `CreateAgentRequest`, `UpdateAgentRequest`
- `CreateWorkflowRunRequest`, `WorkflowRunSummary`
- `WorkflowRunDetails`, `RetryStepRequest`
- `ConnectionRequest`, `TriggerRequest`

#### **API Endpoints by Domain**

**Agent Management**:
```yaml
/api/agents:
  get: # List agents
  post: # Create agent
/api/agents/{agentID}/versions:
  post: # Create version
/api/agents/{agentID}/deploy:
  post: # Deploy version
```

**Workflow Execution**:
```yaml
/api/workflow-runs:
  get: # List runs (paginated)
  post: # Create/start run
/api/workflow-runs/{runID}:
  get: # Get run details
/api/workflow-runs/{runID}/control:
  post: # Control run (pause/resume/cancel)
```

**Worker Management**:
```yaml
/api/workers:
  post: # Register worker
/api/workers/{workerID}/heartbeat:
  put: # Update heartbeat
/api/workers/{workerID}/claim-work:
  post: # Claim work items
```

### Phase 3: Code Generation Integration

1. **Makefile/Build Integration**:
   ```makefile
   .PHONY: generate-api
   generate-api:
   	oapi-codegen -config api/config.yaml api/openapi.yaml
   
   .PHONY: build
   build: generate-api
   	go build ./cmd/server
   ```

2. **CI/CD Integration**:
   - Add API generation step to GitHub Actions
   - Validate OpenAPI spec on PR
   - Check for generated code drift

### Phase 4: Server Implementation

1. **Interface Implementation**:
   ```go
   type APIServer struct {
       db *sql.DB
       // ... other dependencies
   }
   
   // Implement all generated ServerInterface methods
   func (s *APIServer) GetAgents(ctx context.Context, request GetAgentsRequestObject) (GetAgentsResponseObject, error) {
       // Implementation
   }
   ```

2. **Router Integration**:
   ```go
   // Replace current manual routing with generated handler
   apiServer := &APIServer{db: db}
   handler := generated.HandlerWithOptions(apiServer, generated.StdHTTPServerOptions{
       BaseURL: "/api",
       Middlewares: []generated.MiddlewareFunc{
           // Add authentication, logging, etc.
       },
   })
   
   r.Mount("/api", handler)
   ```

### Phase 5: Migration Strategy

1. **Parallel Implementation**: 
   - Keep existing handlers during transition
   - Implement generated interfaces gradually
   - Use feature flags for rollout

2. **Endpoint Mapping**:
   - Map existing `internal/api/router.go` handlers to generated interfaces
   - Update `internal/workflow` handlers to implement generated interfaces
   - Ensure backward compatibility during migration

3. **Testing**:
   - Update integration tests to use generated types
   - Add OpenAPI spec validation tests
   - Ensure all existing functionality works

### Phase 6: Documentation & Tooling

1. **Interactive Documentation**:
   - Host Swagger UI at `/api/docs`
   - Integrate with existing web frontend

2. **Client SDK**:
   - Generate Go client SDK
   - Generate TypeScript/JavaScript SDK for frontend
   - Publish SDKs for external integrators

### **Router Architecture Compatibility**
- Current merged handler approach in `main.go` needs accommodation
- Workflow engine (`/api/workflow-runs`) vs main API routing
- WebSocket endpoint (`/api/ws`) special handling

### **Existing Patterns**
- Query parameter filtering (`?kind=model,action`)
- Pagination support (`?page=1&limit=50`)
- Database transaction patterns
- Error response formatting

### **Integration Points**
- Chi router middleware compatibility
- Database connection injection
- Plugin system integration
- WebSocket upgrade handling

## Success Criteria
- [ ] All 65+ endpoints covered in OpenAPI spec
- [ ] Generated code compiles and passes tests
- [ ] No regression in API functionality
- [ ] Interactive API documentation available
- [ ] Client SDK generation working
- [ ] CI/CD integration complete

## Dependencies
- oapi-codegen v2
- Chi router compatibility
- PostgreSQL schema alignment
- Existing test suite compatibility
