### ISSUE TITLE
feat: integrate GoReleaser into CI pipeline for automated releases

### ISSUE THREAD

**Issue by cedricziel** [cedricziel/mel-agent#67]
## Description

Integrate GoReleaser into the CI/CD pipeline to automate the building and releasing of MEL Agent binaries across multiple platforms and architectures.

## Problem

Currently, there's no automated release process for MEL Agent binaries

Manual releases are time-consuming and error-prone

Users need binaries for different platforms (Linux, macOS, Windows) and architectures (amd64, arm64)

No standardized release artifacts or changelog generation

### GoReleaser Configuration
Create `.goreleaser.yaml` configuration file with:

Cross-platform binary builds for major OS/architecture combinations

Automated changelog generation from commit messages

Release artifact packaging (archives, checksums)

GitHub Releases integration with proper versioning

### CI/CD Integration
Add GitHub Actions workflow for releases:

Trigger on git tags (e.g., `v1.0.0`)

Build binaries for multiple platforms

Generate release notes and changelog

Upload artifacts to GitHub Releases

Sign release artifacts for security

### Supported Platforms
Target platforms and architectures:

```yaml
builds:
  - binary: mel-agent
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
```

### Release Workflow
```yaml
name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version: stable
      - uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

### GoReleaser Configuration
Binary naming and output directory structure

Archive format preferences (tar.gz for Unix, zip for Windows)

Checksum generation (SHA256)

Release notes template and changelog formatting

### CI Pipeline Updates
Release workflow triggered by version tags

Integration with existing test pipeline (ensure tests pass before release)

Environment variables and secrets configuration

Build caching for faster releases

### Documentation Updates
Release process documentation for maintainers

Installation instructions for end users

Version compatibility matrix

Migration guides for breaking changes

### Automated Release Process
Consistent binary builds across platforms

Reduced manual effort and human error

Standardized release artifacts and naming

### Improved User Experience
Easy installation for different platforms

Checksums for integrity verification

Proper versioning and release notes

### Development Workflow
Streamlined release process for maintainers

Automated changelog generation

Integration with existing git workflow

## Acceptance Criteria

- [ ] GoReleaser configuration file created
- [ ] CI workflow for releases implemented
- [ ] Binaries built for Linux, macOS, Windows (amd64, arm64)
- [ ] Release artifacts uploaded to GitHub Releases
- [ ] Checksums generated and included
- [ ] Changelog automatically generated from commits
- [ ] Documentation updated with installation instructions
- [ ] Test release process with pre-release tag

## Configuration Example

Basic `.goreleaser.yaml` structure:

```yaml
project_name: mel-agent

builds:
  - binary: mel-agent
    main: ./cmd/server
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    env: [CGO_ENABLED=0]

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
```

## Additional Considerations

Integration with semantic versioning workflow

Support for pre-release and release candidate builds

Homebrew formula generation for macOS users

Debian/RPM package generation for Linux distributions
