### ISSUE TITLE
feat: create and publish Docker images to GitHub Container Registry (GHCR)

### ISSUE THREAD

**Issue by cedricziel** [cedricziel/mel-agent#68]
## Description

Add Docker containerization support and publish multi-architecture Docker images to GitHub Container Registry (ghcr.io) for easy deployment and distribution of MEL Agent.

## Problem

No containerized distribution of MEL Agent available

Users need to build Docker images manually for deployment

No standardized container images for different architectures

Missing container-based deployment options for production environments

### Docker Images
Create Docker images for different deployment scenarios:

**mel-agent:latest** - Full image with server and worker capabilities

**mel-agent:server** - API server only (no embedded workers)

**mel-agent:worker** - Worker-only image for distributed deployments

### Multi-Architecture Support
Build images for multiple architectures:

linux/amd64 (x86_64)

linux/arm64 (ARM64/aarch64)

linux/arm/v7 (ARM32)

### GitHub Container Registry Integration
Publish images to ghcr.io with proper tagging:

```
ghcr.io/cedricziel/mel-agent:latest
ghcr.io/cedricziel/mel-agent:v1.0.0
ghcr.io/cedricziel/mel-agent:server
ghcr.io/cedricziel/mel-agent:worker
```

### CI/CD Workflow
```yaml
name: Docker Build and Push
on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name \!= 'pull_request' }}
          tags: |
            ghcr.io/cedricziel/mel-agent:latest
            ghcr.io/cedricziel/mel-agent:${{ github.ref_name }}
```

### Dockerfile Creation
Create optimized Dockerfiles:

**Multi-stage builds** for minimal image size

**Distroless or Alpine** base images for security

**Non-root user** for container security

**Health checks** for container monitoring

### Example Dockerfile Structure
```dockerfile
# Build stage
FROM golang:1.21-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o mel-agent ./cmd/server

# Runtime stage
FROM gcr.io/distroless/static-debian11
COPY --from=builder /app/mel-agent /mel-agent
USER nonroot:nonroot
EXPOSE 8080
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD ["/mel-agent", "health"]
ENTRYPOINT ["/mel-agent"]
CMD ["server"]
```

### Image Variants
Create specialized images for different use cases:

**Full Image**: Contains both server and worker capabilities

**Server-Only**: Optimized for API server deployment

**Worker-Only**: Lightweight worker for distributed processing

### Container Configuration
Support configuration via:

Environment variables (existing MEL_* variables)

Config file mounting (/etc/mel-agent/config.yaml)

Command-line arguments through CMD override

### Database Integration
Include database migration support:

Automatic migration on server startup

Migration-only container variant for CI/CD pipelines

Health checks that verify database connectivity

### Easy Deployment
Simple container deployment with docker run or docker-compose

Kubernetes-ready with proper health checks and configuration

Standardized runtime environment across deployments

### Scalability
Separate server and worker images for horizontal scaling

Multi-architecture support for different deployment targets

Optimized images for cloud and edge deployments

### Development Workflow
Consistent development environment with Docker Compose

Easy local testing and integration testing

CI/CD integration for automated builds

## Acceptance Criteria

- [ ] Dockerfile created for multi-stage builds
- [ ] Multi-architecture builds (amd64, arm64)
- [ ] Images published to ghcr.io
- [ ] Server-only and worker-only image variants
- [ ] Health checks implemented
- [ ] Non-root user configuration
- [ ] Environment variable configuration support
- [ ] Docker Compose example for local development
- [ ] Documentation for container deployment
- [ ] CI/CD workflow for automated builds

### Full Server (with embedded workers)
```bash
docker run -d -p 8080:8080 \
  -e DATABASE_URL=postgres://... \
  ghcr.io/cedricziel/mel-agent:latest server
```

### API Server Only
```bash
docker run -d -p 8080:8080 \
  -e DATABASE_URL=postgres://... \
  ghcr.io/cedricziel/mel-agent:server
```

### Remote Worker
```bash
docker run -d \
  -e MEL_SERVER_URL=https://api.example.com \
  -e MEL_WORKER_TOKEN=your-token \
  ghcr.io/cedricziel/mel-agent:worker
```

### Docker Compose
```yaml
version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: agentsaas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      
  mel-agent:
    image: ghcr.io/cedricziel/mel-agent:latest
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/agentsaas?sslmode=disable
    depends_on:
      - postgres
    command: ["server"]
```

## Security Considerations

Use distroless or minimal base images

Run containers as non-root user

Implement proper secrets management

Regular security scanning of images

Signed container images for verification

## Additional Features

Integration with container orchestration (Kubernetes manifests)

Helm charts for Kubernetes deployments

Container monitoring and logging configuration

Resource limits and requests optimization
