### ISSUE TITLE
Implement metrics endpoint for Horizontal Pod Autoscaler (HPA) support

### ISSUE THREAD

**Issue by cedricziel** [cedricziel/mel-agent#72]
## Problem

For effective Kubernetes Horizontal Pod Autoscaler (HPA) scaling decisions, MEL Agent needs to expose comprehensive application-level metrics beyond basic CPU/memory usage. The current implementation lacks visibility into queue depth, worker utilization, and processing performance that would enable intelligent autoscaling.

## Proposed Solution

Implement a `/metrics` endpoint that exposes key performance indicators for HPA scaling decisions.

### Phase 1: Basic Metrics Endpoint
- [ ] Add `/metrics` HTTP endpoint to server and api-server commands
- [ ] Implement JSON metrics response with essential scaling indicators
- [ ] Add metrics endpoint to health check configuration

### Phase 2: Queue-based Metrics (Critical for Scaling)
- [ ] `queue_depth_total` - Number of pending work items by type
- [ ] `queue_wait_time_avg_seconds` - Average time items wait in queue
- [ ] `queue_processing_time_avg_seconds` - Average processing time per item
- [ ] `queue_throughput_per_minute` - Items processed per minute

### Phase 3: Worker Performance Metrics
- [ ] `workers_active_count` - Currently processing workers
- [ ] `workers_idle_count` - Available worker capacity
- [ ] `workers_utilization_percent` - Percentage of workers busy
- [ ] `workers_total_registered` - Total registered workers

### Phase 4: API Performance Metrics
- [ ] `api_requests_per_second` - Request rate
- [ ] `api_response_time_p95_ms` - 95th percentile response time
- [ ] `api_active_connections` - Current HTTP connections
- [ ] `websockets_active_connections` - Active WebSocket connections

### Phase 5: Workflow Metrics
- [ ] `workflows_active_count` - Currently running workflows
- [ ] `workflows_completed_per_minute` - Workflow completion rate
- [ ] `workflows_failed_count` - Failed workflow count (24h)

### Basic Metrics Endpoint
```go
// Add to cmd/server/main.go
r.Get("/metrics", metricsHandler)

func metricsHandler(w http.ResponseWriter, r *http.Request) {
    metrics := map[string]interface{}{
        "timestamp": time.Now().UTC().Format(time.RFC3339),
        "queue": map[string]interface{}{
            "depth_total": getQueueDepth(),
            "wait_time_avg_seconds": getAverageWaitTime(),
        },
        "workers": map[string]interface{}{
            "active_count": getActiveWorkers(),
            "utilization_percent": getWorkerUtilization(),
        },
        "api": map[string]interface{}{
            "requests_per_second": getRequestRate(),
            "response_time_p95_ms": getP95ResponseTime(),
        },
    }
    
    w.Header().Set("Content-Type", "application/json")
    json.NewEncoder(w).Encode(metrics)
}
```

### Queue Metrics Integration
```go
// Modify pkg/execution/engine.go
func (e *DurableExecutionEngine) ClaimWork(...) {
    // ... existing code ...
    
    // Update metrics after claiming work
    updateQueueMetrics(len(items))
    return items, nil
}
```

### API Server HPA
```yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mel-agent-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mel-agent-api
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metric:
        name: mel_api_requests_per_second
      target:
        type: AverageValue
        averageValue: "100"  # Scale up if >100 RPS per pod
```

### Worker HPA
```yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mel-agent-worker-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mel-agent-worker
  minReplicas: 2
  maxReplicas: 20
  metrics:
  - type: External
    external:
      metric:
        name: mel_queue_depth_total
      target:
        type: AverageValue
        averageValue: "10"  # 1 worker per 10 queued items
```

### Prometheus Integration (Phase 6)
- [ ] Add Prometheus metrics library
- [ ] Implement standard Prometheus metrics format
- [ ] Add Grafana dashboard templates
- [ ] Create alerting rules for critical metrics

### Custom Metrics API (Phase 7)
- [ ] Implement Kubernetes custom metrics API adapter
- [ ] Support for custom HPA metrics
- [ ] Advanced scaling policies

## Acceptance Criteria

- [ ] `/metrics` endpoint returns JSON with all essential metrics
- [ ] Metrics accurately reflect current system state
- [ ] Endpoint is performant (<100ms response time)
- [ ] Metrics are updated in real-time as system state changes
- [ ] Documentation includes HPA configuration examples
- [ ] Integration tests verify metrics accuracy
- [ ] Load testing validates metrics under scale

## Priority

**High** - Essential for production Kubernetes deployments that need intelligent autoscaling beyond basic CPU/memory metrics.

## Dependencies

- Existing queue system in `pkg/execution/engine.go`
- Worker registration system
- Health check infrastructure

## Related Issues

- #53 - Horizontal scaling improvements (completed)
- #70 - Redis WebSocket scaling (future)

**Labels:** enhancement, kubernetes, monitoring, scaling, metrics
