### ISSUE TITLE
feat: implement MCP client (action) and server (trigger) nodes for Model Context Protocol integration

### ISSUE THREAD

**Issue by cedricziel** [cedricziel/mel-agent#74]
## Description

Add support for the Model Context Protocol (MCP) by implementing client action nodes and server trigger nodes, enabling MEL Agent to integrate with the growing ecosystem of MCP-compatible tools and services.

## Background

The Model Context Protocol (MCP) is an open standard that enables AI applications to securely connect to external data sources and tools. It provides a standardized way for AI models to access context from various sources like databases, APIs, file systems, and other services.

## Problem

MEL Agent currently lacks integration with MCP-compatible tools and services

Users cannot leverage existing MCP servers for data access and tool execution

No way to expose MEL Agent capabilities as MCP services for other applications

Missing standardized protocol support limits ecosystem integration

### MCP Client Node (Action)
Implement an action node that acts as an MCP client to connect to external MCP servers:

**Node Type**: Action  
**Kinds**: `["action", "tool"]`  
**Purpose**: Execute tools and access resources from MCP servers

### MCP Server Node (Trigger)  
Implement a trigger node that exposes MEL Agent as an MCP server:

**Node Type**: Trigger  
**Kinds**: `["trigger"]`  
**Purpose**: Allow external MCP clients to trigger MEL Agent workflows

#### Configuration Parameters
```yaml
server_uri: "stdio:///path/to/mcp-server"  # or "tcp://localhost:3000"
tools: ["list_files", "read_file", "search"]  # Available tools from server
resources: ["file://", "db://"]  # Available resource patterns
timeout: 30  # Connection timeout in seconds
auth:
  type: "bearer"  # or "none", "basic"
  token: "${MCP_TOKEN}"
```

#### Node Execution Flow
1. Establish connection to MCP server (stdio or TCP)
2. Perform capability negotiation
3. Execute requested tool or access resource
4. Return structured response data
5. Handle connection lifecycle and error recovery

#### Error Handling
Connection timeout and retry logic

Graceful degradation when MCP server unavailable

Validation of tool parameters and responses

Rate limiting and connection pooling

#### Configuration Parameters
```yaml
bind_address: "localhost:3001"  # TCP binding
transport: "tcp"  # or "stdio"
exposed_tools:
  - name: "trigger_workflow"
    description: "Trigger a MEL Agent workflow"
    parameters:
      agent_id: {type: "string", required: true}
      input_data: {type: "object", required: false}
exposed_resources:
  - pattern: "mel://workflows/*"
    description: "Access to workflow definitions"
  - pattern: "mel://agents/*"
    description: "Access to agent configurations"
```

#### Server Capabilities
Expose MEL Agent workflows as MCP tools

Provide access to workflow definitions and agent data

Handle authentication and authorization

Support both stdio and TCP transports

#### MCP Protocol Support
JSON-RPC 2.0 over stdio/TCP transports

Standard MCP message types (initialize, list_tools, call_tool, etc.)

Capability negotiation and version compatibility

Proper error codes and structured responses

#### Message Flow Example
```json
// Client -> Server: Initialize
{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "initialize",
  "params": {
    "protocolVersion": "2024-11-05",
    "capabilities": {
      "tools": {}
    },
    "clientInfo": {
      "name": "mel-agent",
      "version": "1.0.0"
    }
  }
}

// Server -> Client: Tools list
{
  "jsonrpc": "2.0",
  "id": 2,
  "method": "tools/list",
  "result": {
    "tools": [
      {
        "name": "read_file",
        "description": "Read contents of a file",
        "inputSchema": {
          "type": "object",
          "properties": {
            "path": {"type": "string"}
          }
        }
      }
    ]
  }
}
```

### Node Plugin System
Implement as standard MEL Agent node plugins

Support dynamic configuration and connection management

Integrate with existing node kinds system

Use dependency injection for MCP client libraries

### Workflow Integration
MCP client nodes can be used in any workflow step

MCP server triggers can initiate workflow execution

Support for streaming responses and long-running operations

Error propagation and retry policies

### Security Considerations
Secure credential management for MCP connections

Validation of MCP server certificates and identity

Rate limiting and DoS protection for MCP server

Audit logging of MCP tool executions

### Go MCP Library
Research existing Go MCP implementations or create one

JSON-RPC 2.0 library for protocol handling

Transport abstractions for stdio/TCP

Connection pooling and lifecycle management

### Protocol References
- [MCP Specification](https://spec.modelcontextprotocol.io/)
- [MCP TypeScript SDK](https://github.com/modelcontextprotocol/typescript-sdk)
- [MCP Python SDK](https://github.com/modelcontextprotocol/python-sdk)

### Unit Tests
MCP protocol message serialization/deserialization

Connection establishment and error handling

Tool execution and response validation

Server capability negotiation

### Integration Tests
Test with reference MCP server implementations

Validate against MCP compliance test suite

End-to-end workflow execution with MCP nodes

Performance and reliability testing

### Example MCP Servers
File system MCP server for testing

Database MCP server integration

Git repository MCP server

Web API MCP server wrapper

## Acceptance Criteria

- [ ] MCP client node implementation with stdio/TCP transport
- [ ] MCP server node implementation exposing MEL Agent workflows
- [ ] Support for standard MCP protocol messages
- [ ] Configuration validation and error handling
- [ ] Integration with MEL Agent node plugin system
- [ ] Documentation and examples for both node types
- [ ] Unit and integration tests with >80% coverage
- [ ] Example MCP server for testing and development
- [ ] Security review and credential management
- [ ] Performance benchmarks and optimization

### MCP Client Node in Workflow
```yaml
nodes:
  - id: "read_docs"
    type: "mcp_client"
    config:
      server_uri: "stdio:///usr/local/bin/file-server"
      tool: "read_file"
      parameters:
        path: "/docs/README.md"
  
  - id: "process_content"
    type: "openai_chat"
    config:
      model: "gpt-4"
      prompt: "Summarize this documentation: {{read_docs.content}}"
```

### MCP Server Configuration
```yaml
triggers:
  - id: "mcp_webhook"
    type: "mcp_server"
    config:
      bind_address: "localhost:3001"
      exposed_tools:
        - name: "run_analysis"
          workflow_id: "data-analysis-workflow"
          description: "Run data analysis workflow"
```

## Future Enhancements

Integration with MCP registry for server discovery

Support for MCP protocol extensions

Streaming responses and real-time data access

MCP proxy node for server chaining

Integration with popular MCP server implementations (GitHub, Slack, etc.)

## Documentation Requirements

MCP integration guide for users

Node configuration reference

Security best practices for MCP connections

Troubleshooting guide for common MCP issues

Example workflows demonstrating MCP capabilities
