### ISSUE TITLE
feat: add CLI tool to run YAML workflow definitions standalone

### ISSUE THREAD

**Issue by cedricziel** [cedricziel/mel-agent#75]
## Description

Add a CLI command that allows users to execute workflow definitions from YAML files without requiring the full MEL Agent server infrastructure, enabling standalone workflow execution for development, testing, and CI/CD scenarios.

## Problem

Currently, workflows can only be executed through the full MEL Agent server

No way to run workflows locally for development and testing

Difficult to integrate workflows into CI/CD pipelines

Missing standalone execution for simple automation tasks

No quick way to validate workflow definitions

## Proposed Solution

Add a new `run` command to the MEL Agent CLI that can execute YAML workflow definitions directly:

```bash
# Run a workflow from a YAML file
mel-agent run workflow.yaml

# Run with input data
mel-agent run workflow.yaml --input '{"key": "value"}'
mel-agent run workflow.yaml --input-file input.json

# Run with environment variable substitution
mel-agent run workflow.yaml --env

# Validate workflow without executing
mel-agent run workflow.yaml --validate-only

# Output structured results
mel-agent run workflow.yaml --output json
mel-agent run workflow.yaml --output yaml
```

### CLI Command Structure
```go
var runCmd = &cobra.Command{
    Use:   "run [workflow.yaml]",
    Short: "Execute a workflow definition from a YAML file",
    Long:  `...`,
    Args:  cobra.ExactArgs(1),
    Run:   runWorkflow,
}
```

### YAML Workflow Definition Format
```yaml
# workflow.yaml
version: "1.0"
name: "data-processing"
description: "Process data and generate report"

variables:
  input_path: "${INPUT_PATH:-./data.json}"
  output_path: "${OUTPUT_PATH:-./output.json}"

nodes:
  - id: "read_file"
    type: "file_read"
    config:
      path: "{{variables.input_path}}"
  
  - id: "process_data"
    type: "openai_chat"
    config:
      model: "gpt-4"
      prompt: "Analyze this data: {{read_file.content}}"
    depends_on: ["read_file"]
  
  - id: "save_result"
    type: "file_write"
    config:
      path: "{{variables.output_path}}"
      content: "{{process_data.response}}"
    depends_on: ["process_data"]

outputs:
  result: "{{process_data.response}}"
  output_file: "{{variables.output_path}}"
```

### Execution Engine
Lightweight workflow execution engine without database dependencies

In-memory workflow state management

Support for all existing node types and plugins

Variable substitution and templating

Dependency resolution and execution ordering

### Configuration Management
Support for environment variable substitution

External configuration file support

Credential management for API keys and tokens

Plugin loading and initialization

### Input/Output Handling
JSON and YAML input file support

Command-line input parameter passing

Structured output formats (JSON, YAML, text)

Exit codes for success/failure scenarios

### Workflow Validation
Syntax validation of YAML workflow definitions

Node type and configuration validation

Dependency cycle detection

Missing plugin detection

### Variable Substitution
Environment variable expansion with `${VAR}` syntax

Default value support with `${VAR:-default}`

Runtime variable resolution

Template processing with `{{node.output}}` syntax

### Error Handling
Detailed error messages with line numbers

Node execution error reporting

Dependency resolution error handling

Graceful handling of missing plugins or credentials

### Output Options
Human-readable progress output

Structured JSON/YAML output for automation

Quiet mode for CI/CD integration

Verbose mode for debugging

### Basic Execution
```bash
# Run a simple workflow
mel-agent run examples/hello-world.yaml

# Run with custom input
mel-agent run data-pipeline.yaml --input '{"source": "database"}'

# Run with input file
mel-agent run etl-workflow.yaml --input-file config.json
```

### Validation and Testing
```bash
# Validate workflow syntax without execution
mel-agent run workflow.yaml --validate-only

# Dry run to see execution plan
mel-agent run workflow.yaml --dry-run

# Check for missing dependencies
mel-agent run workflow.yaml --check-deps
```

### Output and Formatting
```bash
# Output results as JSON
mel-agent run workflow.yaml --output json

# Save output to file
mel-agent run workflow.yaml --output-file results.json

# Quiet mode for scripts
mel-agent run workflow.yaml --quiet
```

### Environment Integration
```bash
# Use environment variables
export API_KEY="sk-..."
export INPUT_FILE="./data.csv"
mel-agent run workflow.yaml --env

# Load variables from .env file
mel-agent run workflow.yaml --env-file .env
```

### Standalone Execution Engine
Create a lightweight execution engine that doesn't require:

Database connectivity

Web server infrastructure

Worker processes

Trigger scheduling

### Plugin System Integration
Load and initialize node plugins

Support for both built-in and external plugins

Plugin dependency management

Configuration validation per plugin

### State Management
In-memory workflow state tracking

Node output storage and retrieval

Variable resolution and caching

Error state preservation

### Templating Engine
Support existing MEL Agent templating syntax

Variable and output substitution

Conditional logic support

Helper functions for common operations

### Global Configuration
```yaml
# ~/.mel-agent/config.yaml
plugins:
  - path: "./plugins"
  - path: "/usr/local/lib/mel-agent/plugins"

credentials:
  openai_api_key: "${OPENAI_API_KEY}"
  github_token: "${GITHUB_TOKEN}"

defaults:
  timeout: 300
  retry_attempts: 3
```

### Workflow-Specific Configuration
```yaml
# workflow.yaml
config:
  timeout: 600
  max_retries: 5
  env_file: ".env"
  
plugins:
  - name: "custom_plugin"
    config:
      setting: "value"
```

### Unit Tests
YAML parsing and validation

Workflow execution engine

Variable substitution logic

Error handling scenarios

### Integration Tests
End-to-end workflow execution

Plugin loading and initialization

File I/O operations

API integrations with mocked services

### Example Workflows
Simple data processing workflow

API integration workflow

File manipulation workflow

Multi-step automation workflow

## Acceptance Criteria

- [ ] CLI `run` command implementation
- [ ] YAML workflow definition parser
- [ ] Standalone execution engine without database dependency
- [ ] Support for all existing node types
- [ ] Variable substitution and templating
- [ ] Input/output handling (JSON, YAML, CLI args)
- [ ] Workflow validation and error reporting
- [ ] Environment variable integration
- [ ] Plugin system integration
- [ ] Comprehensive error messages and exit codes
- [ ] Documentation and example workflows
- [ ] Unit and integration tests

### Development Workflow
Quick iteration and testing of workflows

Local development without full server setup

Easy debugging and troubleshooting

Version control friendly workflow definitions

### CI/CD Integration
Workflow execution in automated pipelines

Consistent environment across development and production

Easy integration with existing build systems

Portable workflow definitions

### Operational Simplicity
No infrastructure setup for simple automation

Lightweight deployment for edge cases

Easy sharing and collaboration on workflows

Clear separation between development and production environments

### Data Processing Pipeline
```bash
# Process daily sales data
mel-agent run pipelines/daily-sales.yaml \
  --input '{"date": "2024-01-15"}' \
  --env-file production.env
```

### Code Quality Checks
```bash
# Run code analysis workflow in CI
mel-agent run .github/workflows/code-quality.yaml \
  --input '{"commit": "'$GITHUB_SHA'"}' \
  --output json
```

### Content Generation
```bash
# Generate documentation
mel-agent run content/generate-docs.yaml \
  --input-file config.json \
  --output-file docs/generated.md
```

## Future Enhancements

Interactive workflow builder CLI

Workflow debugging and step-through execution

Integration with workflow registries

Support for workflow composition and imports

Performance profiling and optimization tools
