### ISSUE TITLE
feat: implement Docker action node type for containerized workflow execution

### ISSUE THREAD

**Issue by cedricziel** [cedricziel/mel-agent#76]
## Description

Implement a Docker action node type that enables workflows to execute containerized workloads, providing isolated execution environments, language-agnostic processing, and integration with the Docker ecosystem.

## Problem

Current workflow nodes are limited to Go-based plugins and built-in functionality

No way to execute code in different programming languages or runtime environments

Lack of isolated execution environments for potentially unsafe or resource-intensive operations

Missing integration with existing Docker-based tools and services

No support for complex dependencies or system-level operations

## Proposed Solution

Create a Docker action node that can:

Execute arbitrary Docker containers as workflow steps

Mount data volumes for input/output processing

Configure resource limits and security constraints

Support custom Docker images and registries

Handle container lifecycle and cleanup

### Node Configuration
```yaml
node:
  id: "process_data"
  type: "docker"
  config:
    image: "python:3.11-slim"
    command: ["python", "/app/process.py"]
    working_dir: "/app"
    environment:
      - "API_KEY={{secrets.api_key}}"
      - "INPUT_FILE=/data/input.json"
    volumes:
      - source: "{{workspace}}/data"
        target: "/data"
        read_only: false
      - source: "{{node_files}}/scripts"
        target: "/app"
        read_only: true
    resources:
      memory: "512m"
      cpu: "0.5"
    timeout: 300
    network: "none"  # or "bridge", "host"
    registry:
      username: "{{secrets.docker_username}}"
      password: "{{secrets.docker_password}}"
      server: "ghcr.io"
```

### Advanced Configuration
```yaml
node:
  id: "ml_training"
  type: "docker"
  config:
    image: "tensorflow/tensorflow:2.13.0-gpu"
    command: ["python", "/workspace/train.py"]
    gpu: true
    volumes:
      - source: "{{outputs.data_prep.dataset_path}}"
        target: "/workspace/data"
        read_only: true
      - source: "{{workspace}}/models"
        target: "/workspace/models"
        read_only: false
    environment:
      - "CUDA_VISIBLE_DEVICES=0"
      - "MODEL_NAME={{variables.model_name}}"
    resources:
      memory: "8g"
      cpu: "4"
      gpu_count: 1
    security:
      privileged: false
      user: "1000:1000"
      drop_capabilities: ["ALL"]
      add_capabilities: []
    cleanup: true  # Remove container after execution
```

#### Container Execution
Support for any Docker image from public or private registries

Custom command and argument specification

Working directory configuration

Environment variable injection with template support

#### Volume Management
Workspace volume mounting for persistent data

Input/output data exchange between host and container

Script and configuration file mounting

Temporary volume creation and cleanup

#### Resource Management
Memory and CPU limits configuration

GPU access and allocation (with nvidia-docker support)

Network isolation options (none, bridge, host)

Execution timeout with graceful termination

#### Security Controls
Non-privileged container execution by default

User and group ID mapping

Capability dropping for enhanced security

Read-only filesystem options

Network isolation for untrusted workloads

#### Registry Integration
Support for private Docker registries

Authentication with username/password or tokens

Image pulling and caching

Multi-architecture image support

### Docker Client Integration
```go
package docker

import (
    "context"
    "github.com/docker/docker/api/types"
    "github.com/docker/docker/client"
)

type DockerNode struct {
    client *client.Client
    config DockerConfig
}

type DockerConfig struct {
    Image       string            `yaml:"image"`
    Command     []string          `yaml:"command"`
    WorkingDir  string            `yaml:"working_dir"`
    Environment []string          `yaml:"environment"`
    Volumes     []VolumeMount     `yaml:"volumes"`
    Resources   ResourceLimits    `yaml:"resources"`
    Network     string            `yaml:"network"`
    Timeout     int               `yaml:"timeout"`
    GPU         bool              `yaml:"gpu"`
    Security    SecurityConfig    `yaml:"security"`
}

func (n *DockerNode) Execute(ctx context.Context, input map[string]interface{}) (map[string]interface{}, error) {
    // 1. Pull image if needed
    // 2. Create container with configuration
    // 3. Start container and monitor execution
    // 4. Collect output and logs
    // 5. Cleanup container and volumes
}
```

### Volume Management
```go
type VolumeMount struct {
    Source   string `yaml:"source"`
    Target   string `yaml:"target"`
    ReadOnly bool   `yaml:"read_only"`
}

// Template resolution for volume sources
func (v *VolumeMount) ResolveSource(ctx WorkflowContext) (string, error) {
    // Resolve templates like {{workspace}}, {{outputs.node.path}}, etc.
    return templateEngine.Render(v.Source, ctx)
}
```

### Resource Limits
```go
type ResourceLimits struct {
    Memory   string `yaml:"memory"`   // "512m", "2g"
    CPU      string `yaml:"cpu"`      // "0.5", "2"
    GPUCount int    `yaml:"gpu_count"`
}

type SecurityConfig struct {
    Privileged       bool     `yaml:"privileged"`
    User             string   `yaml:"user"`          // "1000:1000"
    DropCapabilities []string `yaml:"drop_capabilities"`
    AddCapabilities  []string `yaml:"add_capabilities"`
}
```

### Output Handling
```go
type DockerOutput struct {
    ExitCode int                    `json:"exit_code"`
    Stdout   string                 `json:"stdout"`
    Stderr   string                 `json:"stderr"`
    Files    map[string]interface{} `json:"files"`    // Files from output volumes
    Metrics  ContainerMetrics       `json:"metrics"`  // Resource usage
}

type ContainerMetrics struct {
    Duration      int64   `json:"duration_ms"`
    MemoryUsage   int64   `json:"memory_usage_bytes"`
    CPUUsage      float64 `json:"cpu_usage_percent"`
    NetworkRX     int64   `json:"network_rx_bytes"`
    NetworkTX     int64   `json:"network_tx_bytes"`
}
```

### Data Processing
```yaml
nodes:
  - id: "process_csv"
    type: "docker"
    config:
      image: "pandas/pandas:latest"
      command: ["python", "/scripts/process.py"]
      volumes:
        - source: "{{inputs.csv_file}}"
          target: "/data/input.csv"
          read_only: true
        - source: "{{workspace}}/output"
          target: "/data/output"
          read_only: false
        - source: "./scripts/data_processing.py"
          target: "/scripts/process.py"
          read_only: true
      environment:
        - "OUTPUT_FORMAT=json"
```

### Machine Learning
```yaml
nodes:
  - id: "train_model"
    type: "docker"
    config:
      image: "pytorch/pytorch:2.0.1-cuda11.7-cudnn8-runtime"
      command: ["python", "/workspace/train.py"]
      gpu: true
      volumes:
        - source: "{{outputs.data_prep.training_data}}"
          target: "/workspace/data"
          read_only: true
        - source: "{{workspace}}/models"
          target: "/workspace/models"
          read_only: false
      resources:
        memory: "16g"
        cpu: "8"
        gpu_count: 1
      timeout: 3600
```

### Code Analysis
```yaml
nodes:
  - id: "security_scan"
    type: "docker"
    config:
      image: "securecodewarrior/docker-security-scanner"
      command: ["scan", "/code"]
      volumes:
        - source: "{{inputs.source_code}}"
          target: "/code"
          read_only: true
        - source: "{{workspace}}/reports"
          target: "/reports"
          read_only: false
      network: "none"
      security:
        privileged: false
        user: "1000:1000"
        drop_capabilities: ["ALL"]
```

### Web Scraping
```yaml
nodes:
  - id: "scrape_data"
    type: "docker"
    config:
      image: "selenium/standalone-chrome:latest"
      command: ["python", "/app/scraper.py"]
      volumes:
        - source: "./scrapers/web_scraper.py"
          target: "/app/scraper.py"
          read_only: true
        - source: "{{workspace}}/scraped_data"
          target: "/app/output"
          read_only: false
      environment:
        - "TARGET_URL={{variables.scrape_url}}"
        - "HEADLESS=true"
      resources:
        memory: "2g"
        cpu: "1"
      timeout: 600
```

### Container Security
Default to non-privileged execution

Drop all capabilities by default

Use specific user IDs instead of root

Read-only root filesystem when possible

Resource limits to prevent DoS

### Network Security
Default to no network access

Configurable network policies

No access to host network by default

Optional bridge network with restrictions

### Data Security
Secure temporary file handling

Cleanup of sensitive data after execution

Volume mount validation

Input sanitization for commands and environment variables

### Registry Security
Secure credential storage for private registries

Image signature verification (when available)

Base image vulnerability scanning integration

Pull policy configuration (always, if-not-present, never)

### Container Failures
Non-zero exit codes propagated as errors

Timeout handling with graceful termination

OOM killer detection and reporting

Resource limit exceeded errors

### Infrastructure Failures
Docker daemon connectivity issues

Image pull failures with retry logic

Volume mount permission errors

Network connectivity problems

### Configuration Errors
Invalid image names or tags

Malformed resource specifications

Volume mount path validation

Environment variable injection errors

### Unit Tests
Docker configuration parsing and validation

Volume mount resolution and templating

Resource limit specification parsing

Security configuration validation

### Integration Tests
End-to-end container execution

Volume mounting and data exchange

Resource limit enforcement

Network isolation verification

GPU access testing (when available)

### Security Tests
Privilege escalation prevention

Container escape attempts

Resource exhaustion scenarios

Malicious input handling

### Image Management
Local image caching

Parallel image pulling

Image cleanup policies

Multi-stage build optimization

### Resource Optimization
Container resource monitoring

Memory usage tracking

CPU utilization reporting

Disk space management

### Execution Optimization
Container startup time optimization

Volume mount performance

Network throughput consideration

Parallel container execution

## Acceptance Criteria

- [ ] Docker action node implementation
- [ ] Support for arbitrary Docker images
- [ ] Volume mounting with template resolution
- [ ] Resource limits and security controls
- [ ] Environment variable injection
- [ ] Registry authentication support
- [ ] GPU support (when available)
- [ ] Comprehensive error handling
- [ ] Container cleanup and lifecycle management
- [ ] Output collection (stdout, stderr, files)
- [ ] Resource usage metrics
- [ ] Security controls and validation
- [ ] Unit and integration tests
- [ ] Documentation and examples

## Dependencies

Docker Engine API client for Go

Template engine for variable resolution

Volume management utilities

Resource monitoring libraries

Security policy enforcement

## Documentation Requirements

Docker node configuration reference

Security best practices guide

Performance optimization tips

Troubleshooting common Docker issues

Example workflows for different use cases

GPU setup and configuration guide

Private registry integration guide

## Future Enhancements

Docker Compose support for multi-container workflows

Kubernetes integration for scalable execution

Container image building within workflows

Integration with CI/CD pipeline tools

Advanced networking configurations

Custom container runtime support (containerd, podman)

Container registry scanning integration
